import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav  style={{background: "teal" , padding:20, display:"flex", alignItems:"center",justifyContent:"center"}}>
          <Link style={{margin:10}} href="/">Home</Link>
          <Link style={{margin:10}} href="/posts">Posts</Link>
          <Link style={{margin:10}} href="/products">products</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
